### ISSUE TITLE
stdout/err logs not rotating for Tomcat apps

### ISSUE THREAD

**Issue by brownc** [sapia-oss/corus#15]
the stdout/err logs rotating request was implemented on Corus 4.3.  However it looks like due to a bug, even on current 4.5.2 for Tomcat applications specifiaclly the log rotation is not taking place, leading to large log files in the process home.

Workaround:

conf add –p corus.process.log.rolling=true [-cluster]

Yanick aware.

**Comment by yduchesne** [comment]
Fixed in new branch, as part of a new Tomcat sample module: https://github.com/sapia-oss/corus/tree/feature/tomcat-sample/samples/corus_sample_tomcat

Basically, it's really a Tomcat configuration issue. The solution will be documented on Sapia's website.
