### ISSUE TITLE
conf add -p some_file forces .properties file suffix - -t doesn't

### ISSUE THREAD

**Issue by brownc** [sapia-oss/corus#17]
Some inconsistency when using conf add with files has come to light whilst working on chef deployment recipes.

To successfully import a file full of properties (i.e. "conf add -p my_file") - the my_file must end in .properties.  If I call my file something like "my.props" - it fails as follows:

[phellmscorapi001.karmalab.net:33000@phellmscorapi001]>>  conf add -p test.p -clear
Input error executing command 'conf' ==> Invalid property format; expected: <name>=<value>

If we rename the file test.properties:

[phellmscorapi001.karmalab.net:33000@phellmscorapi001]>>  conf add -p test.properties -clear
[phellmscorapi001.karmalab.net:33000@phellmscorapi001]>>  

No error all good.

It's mildly irritating if you're generating files on the fly like "corus.props.in" as I tried to but not insurmountable.

However, same command but for tags - the file can be called anything, as long as you include a / in the path by the look of it.

Where am I going with this?  Consistency

Can we do anything to make the activities under conf add (whether for tags or properties) more consistent?  For example, if we want to use a file can we specify maybe a "-f" flag, that points to the path of the file?

It would fix the OCD issue I have seen that's not major, it would bring consistency across tags and properties, and thus make things simpler.

Thoughts?

**Comment by yduchesne** [comment]
Spot on. Fix will be done.

**Comment by yduchesne** [comment]
works in 4.6b:

conf add -p -f some.props 
conf add -t -f some.tags -clear
