### ISSUE TITLE
conf add -clear doesn't work for tags

### ISSUE THREAD

**Issue by brownc** [sapia-oss/corus#18]
Whilst the man page clearly states for properties only, it would be much more consistent (and easier when working in chef to stop writing similar but every so slightly different blocks of code ;-) such that -clear (when used with a file) works for both tags and properties.

Could this be enabled?

**Comment by yduchesne** [comment]
This will be fixed. Makes sense.

**Comment by yduchesne** [comment]
Fixed in 4.6b
