### ISSUE TITLE
Dependant CLI Command Params Not Validated

### ISSUE THREAD

**Issue by brownc** [sapia-oss/corus#19]
Follow up from Google Code Bug 29: https://code.google.com/p/sapia/issues/detail?id=29

Consider the following:

>> conf add -t /path.to/my.tags.properties -clear

The command will succeed and add the new tags.  It will *not* however clear the existing tags.  I would expect this command to fail as currently (I've naturally raised a feature request) you can only use -clear on a -p properties files.

Can we extend the fix from 29, to ensure that where there are dependant options in commands, they're validated?

**Comment by yduchesne** [comment]
Will fix that

**Comment by yduchesne** [comment]
Fixed in 4.6b
