### ISSUE TITLE
corus can't find process even the process already started.

### ISSUE THREAD

**Issue by ytao-expedia** [sapia-oss/corus#22]
runAs()
{
    SUDOER=$1
    shift
    echo $LPSO_TEST_PW | sudo -S -u $SUDOER -i "$@"
}

if ! mount | grep "/data/ssl"; then
    if ! runAs root mount -o nolock,timeo=5,retrans=5,actimeo=10,retry=5 -t nfs chelliklbrep001:/data/ssl /opt/app/deploymenthome; then
        exit 1
    fi
fi

if !  runAs corus coruscli -c "conf add -p corus.env=sslst05A -cluster"; then
    exit 1
fi

if ! runAs corus /opt/app/deploymenthome/releng/corus-deploy.sh -p HotelGrid -b $BRANCH -r $REL -v $PACKAGE_VERSION -s deploy-qa.corus; then
    exit 1
fi

if !  runAs corus  coruscli -c "exec -d hotelGrid -v $BRANCH -n locator -p default -i 1 -cluster -w"; then
    coruscli -c ps -cluster
    exit 1
fi

if ! runAs corus coruscli -c ""exec -d hotelGrid -v $BRANCH -n server -p default -i 4 -cluster -w""; then
    coruscli -c ps -cluster
    exit 
fi
chelliklbrep001:/data/ssl on /opt/app/deploymenthome type nfs (rw,vers=4,addr=10.187.64.32,clientaddr=10.208.12.199)
Preparing staging directory...
Downloading HotelGrid-v10.0-release-283980.zip...
Expanding deployment scripts from distribution archive...
Executing deployment script via Corus...
Copyright 2014-2015 Expedia, Inc. All rights reserved.
EXPEDIA PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
Copyright 2014-2015 Expedia, Inc. All rights reserved.
EXPEDIA PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
----- Stopping all processes...
Waiting for process termination, please stand by...
Process(es) terminated.
----- TODO: Remove once kill -w bug is fixed!!!
----- Undeploying all Corus distributions...
UndeployTask >> Undeploying distribution [hotelGrid-v10.0]
UndeployTask >> Undeployment successful
----- Deploying HotelGrid distribution...
Deploying: HotelGrid-v10.0-release-283980.zip
Distribution file uploaded, proceeding to deployment completion
DeployTask >> Deploying: HotelGrid-v10.0-release-283980.zip.143050708341230
DeployTask >> Distribution added to Corus
Batch deployment completed
----- Setting environment properties...
Process execution requested for: [dist=hotelGrid, version=v10.0, process=initialize, profile=default]
----- Deploying Locator execution configuration...
----- Deploying Server execution configuration...
*** DEPLOYMENT COMPLETED ***
Done.
Process execution requested for: [dist=hotelGrid, version=v10.0, process=locator, profile=default]
org.sapia.console.AbortException: Error occurred
	at org.sapia.corus.client.cli.CliContextImpl.createAndAddErrorFor(CliContextImpl.java:71)
	at org.sapia.corus.client.cli.command.CorusCliCommand.execute(CorusCliCommand.java:139)
	at org.sapia.corus.client.cli.command.Exec.doExecute(Exec.java:42)
	at org.sapia.corus.client.cli.command.CorusCliCommand.execute(CorusCliCommand.java:124)
	at org.sapia.corus.client.cli.Interpreter.eval(Interpreter.java:247)
	at org.sapia.corus.client.cli.Interpreter.eval(Interpreter.java:198)
	at org.sapia.corus.client.cli.CorusCli.main(CorusCli.java:191)
Caused by: java.lang.IllegalStateException: Expected number of processes not started. Got: 1, expected: 2
	at org.sapia.corus.client.cli.command.AbstractExecCommand.waitForProcessStartup(AbstractExecCommand.java:164)
	at org.sapia.corus.client.cli.command.exec.ExecProcessByDescriptors.doExecute(ExecProcessByDescriptors.java:71)
	at org.sapia.corus.client.cli.command.CorusCliCommand.execute(CorusCliCommand.java:124)
	... 5 more
================================================================================
 Host: 10.208.41.23:33000                                                       
                                                                                
 Distribution    Versio  Profile  Name        PID            OS PI  Status   
                 n                                           D               
--------------------------------------------------------------------------------
 hotelGrid       v10.0   default  initialize  1505010028531  26383  shutd.   
--------------------------------------------------------------------------------
 hotelGrid       v10.0   default  locator     1505010030239  26560  act.     
================================================================================
 Host: 10.208.41.24:33000                                                       
                                                                                
 Distribution    Versio  Profile  Name        PID            OS PI  Status   
                 n                                           D               
--------------------------------------------------------------------------------
 hotelGrid       v10.0   default  initialize  1505010028583  10016  shutd.   
--------------------------------------------------------------------------------
 hotelGrid       v10.0   default  locator     1505010030288  10054  act.     
[SSH] exit-status: 1

**Comment by ytao-expedia** [comment]
This is on corus 4.5.1

**Comment by yduchesne** [comment]
Could not reproduce.
