### ISSUE TITLE
Support for spaces in config overrides

### ISSUE THREAD

**Issue by brownc** [sapia-oss/corus#23]
This one's come up before.

Long story short:

- In coruscli, you can set key="value with space in" and it sets
- However when Corus goes to start up the app, it doesn't get quoted.  Thus, you'll get 'key=value with space in it" and Java will try and look for main() in "with" - which fubars

What do we need:

- Either support for detecting if there's a space in the value, and if so, surrounding it in quotes when launching the process
- Or removal of accepting values with spaces in for conf add, even if quoted

**Comment by yduchesne** [comment]
Fixed in 4.7-RC2, will thus be in 4.7 ;)

**Comment by brownc** [comment]
Which option - you didn't say on GitHub?

--
Chris B
Sent from my iPhone - please excuse any typos

On 15 May 2015, at 21:19, yduchesne <notifications@github.com> wrote:

Fixed in 4.7-RC2, will thus be in 4.7 ;)

—
Reply to this email directly or view it on GitHub
<https://github.com/sapia-oss/corus/issues/23#issuecomment-102516217>.

**Comment by yduchesne** [comment]
Auto-enclosing, no exclusion. Works with "$@". Happy? :-)

**Comment by brownc** [comment]
Yup sounds great mate. Just needed closure ;)

--
Chris B
Sent from my iPhone - please excuse any typos

On 16 May 2015, at 01:21, yduchesne <notifications@github.com> wrote:

Auto-enclosing, no exclusion. Works with "$@". Happy? :-)
On May 15, 2015 3:21 PM, "brownc" <notifications@github.com> wrote:

> Which option - you didn't say on GitHub?
>
> --
> Chris B
> Sent from my iPhone - please excuse any typos
>
> On 15 May 2015, at 21:19, yduchesne <notifications@github.com> wrote:
>
> Fixed in 4.7-RC2, will thus be in 4.7 ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sapia-oss/corus/issues/23#issuecomment-102516217>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sapia-oss/corus/issues/23#issuecomment-102538100>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/sapia-oss/corus/issues/23#issuecomment-102553165>.
