### ISSUE TITLE
Diagnostic should return an error when no package is deployed

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#42]
To protect from the situation when a new corus instances is dynamically created but no package deployed to it, we would need a way to activate a protection mechanism for the diagnostic API to report this situation.

The expected behavior is the following:
- when there is no package deployed, the diagnostic API should return an HTTP 503 Service Unavailable error
- we should be able to define a configurable grace period after which the diagnostic API returns an error
- this new functionality would need to be activated by configuration 
- this check, if activated, should be also tracking moments when a package gets undeployed

**Comment by yduchesne** [comment]
Done
