### ISSUE TITLE
Sorting of files in the corus http console seems screwed up

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#5]
BUG: Testing this new feature in corus 4.5.1 showed unexpected results in how the sorting behaved.

ENHANCEMENT: Sorting in only one way: ascending. Would be more natural to have ascending/descending sorting available when we click multiple times on the header: flipping the ordering on subsequent clicks.

**Comment by yduchesne** [comment]
Fixed as part of upcoming 4.5.2
