### ISSUE TITLE
Cannot deploy distribution if empty directory exists

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#6]
Corus version: Observed on 4.4.3 and 4.5.1

When an issue prevents a distribution to be deployed in corus (for example when the zip file is corrupted or incomplete), the system still create the directory structure under deploy/{domain}/{dist-name}/{dist-version}.

On the next attempt to deploy the same distribution, corus returns an error saying that the distribution is already deployed. The workaround is to manually go on the filesystem and delete the existing directories.

Either the check for the distribution existence should not only rely on the file system structure, or the check on the disk should not consider the presence of the directories (without any file) as an error condition.

**Comment by yduchesne** [comment]
This should be fixed given the changes introduced in 4.6b
