### ISSUE TITLE
Corus config SSL settings reveals sensitive data via CorusUI

### ISSUE THREAD

**Issue by brownc** [sapia-oss/corus#7]
What steps will reproduce the problem?
1. Install >= 4.5
2. Configure Corus to run on SSL port
3. Navigate a browser to https://SERVER:PORT/files/config/corus.properties?action=list

What version of the product are you using? On what operating system?

Applies to >= 4.5

Please provide any additional information below.

Passwords for keystores and keys are visible due to them being in plain test in the core file.  This is a major security issue.

Please see attached screenshot file
![screen shot 2015-02-11 at 13 52 04](https://cloud.githubusercontent.com/assets/3911430/6148466/9fb3fba6-b1f9-11e4-9346-51d866564219.png)

**Comment by yduchesne** [comment]
This is fixed as part of upcoming 4.5.2
